{% set version = "1.22.0" %}

package:
  name: csa
  version: {{ version }}

source:
  url: https://github.com/sakov/csa-c/archive/v{{ version }}.tar.gz
  sha256: b6d6ebeea146e09fc7aef827a3a3b22b7af674c2f0c67169c2275237e54c0c02

build:
  number: 2002
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:

test:
  commands:
    - csabathy -V
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://github.com/sakov/csa-c
  license: BSD 2-Clause
  summary: 'Cubic Spline Approximation'

extra:
  recipe-maintainers:
    - ocefpaf
