appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: PSOtNiD7Ev9KVbdenhDwPkqxdkJLE5IQJN4nzN66UOoQQuK/gJEsizHj2NikR+7mljUwsfiEjeZV/svFnwxBh8QWHpovmpgsJky9yWUn8BBTsSodDM0kugwFmV+6fTplj+kr2+IP+LCaZJn7hfeBssj6Jncc9bRuvjlJFca60m8jfPRmwavWAz9bOLEbiV9p170WU7TNL15w/HmMd0rZ7BpW1OT/LYbzzY6LJ30Tdx8vG77rDC6SXOpvFvhgcYn74WHHh2jBz8Uf0YnlrqjFk92lZcu3liF0qL57c8QEeNlu05g8em0eUvJbXriYj6s8doomjRmASkheAzg8moxaj7rgR2301JILGxsbR1REM0+1ChhgZhkTh2SScsPIWJMDHbBhA+B0HJc/3+1EM/HGeDFd61xt15cxX3JNChzchxW5HwRjIJwLMfLBrD1fnlgAcQz9o4iW4c0iHrM+UxntPnMMnO7asYo1/jbsbYQFM8B3/no4ptjVsTh02IkEn5lDjudvkVhjstXl+cAuQh+H3oFW4apB1KHF/Vk9ixWB1a5vDHMZ0W9Hc/1dGJMN8b/jxjCOCac55cRoaBPVl6raSrs9pXIwbwFWrzxIQtttt/XNw5Gx8o/m+cJ6oiT0hmZjQcjrXgvd13LPtXUttzEIV4/Ykc12I1lp6B8Wy/YpQeA=}
conda_forge_output_validation: true
